databaseChangeLog:
  - changeSet:
      id: 1.3.0-application-create-table
      author: Maksim Aminov
      changes:
        - createTable:
            tableName: application
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_application
                  name: id
                  type: UUID
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: DATETIME
              - column:
                  constraints:
                    nullable: false
                  name: status
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: type
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created
                  type: TIMESTAMP
              - column:
                  constraints:
                    nullable: false
                  name: email
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: patronymic
                  type: VARCHAR(255)
              - column:
                  name: birth_date
                  type: DATE
              - column:
                  name: passport
                  type: VARCHAR(255)
              - column:
                  name: citizenship
                  type: VARCHAR(255)
              - column:
                  name: telegram
                  type: VARCHAR(255)
              - column:
                  name: in_serbia
                  type: BOOLEAN
              - column:
                  name: enter_date
                  type: DATE
              - column:
                  name: address
                  type: VARCHAR(255)
              - column:
                  name: phone
                  type: VARCHAR(255)
              - column:
                  name: residence_required
                  type: BOOLEAN
              - column:
                  name: occupation
                  type: VARCHAR(255)
              - column:
                  name: has_experience
                  type: BOOLEAN
              - column:
                  name: experience
                  type: TEXT
              - column:
                  name: languages
                  type: TEXT
              - column:
                  name: skills
                  type: TEXT
              - column:
                  name: goal
                  type: TEXT
              - column:
                  name: bio
                  type: TEXT
              - column:
                  name: refuse_reason
                  type: TEXT
  - changeSet:
      id: 1.3.0-application-add-column-comment
      author: Maksim Aminov
      changes:
        - addColumn:
            tableName: application
            columns:
              - column:
                  name: comment
                  type: TEXT
