import org.yaml.snakeyaml.Yaml

import java.nio.file.Files
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

buildscript {
    dependencies {
        classpath("org.yaml:snakeyaml:2.2")
    }
    repositories {
        mavenCentral()
    }
}

ext {
    SPRING_VERSION = "3.5.16"
    SPRING_SECURITY_VERSION = "6.5.11"
    SPRING_AI_VERSION = "1.1.8"
    POSTGRESQL_VERSION = "42.7.11"
    THYMELEAF_VERSION = "3.1.5.RELEASE"
    LOG4J2_VERSION = "2.25.4"
    KOTLINX_VERSION = "1.10.2"
    OKHTTP_VERSION = "5.3.0"
    JACKSON_KOTLIN_VERSION = "2.21.5"
    JAKARTA_VALIDATION_VERSION = "3.1.1"
}

ext.resolveApiVersion = { String openApiPath ->
    println("OpenAPI path: ${openApiPath}")
    def file = new File(openApiPath).newInputStream()
    def yaml = new Yaml().load(file)
    return "${yaml.info.version}"
}

ext.downloadOpenApiFile = { String openApiUrl, String outputPath ->
    // Ensure the directory exists
    def outputDir = new File(outputPath).parentFile
    if (!outputDir.exists()) {
        outputDir.mkdirs()
    }

    println "Downloading OpenAPI file from: $openApiUrl"
    new URI(openApiUrl).toURL().withInputStream { inputStream ->
        Files.copy(inputStream, Paths.get(outputPath), StandardCopyOption.REPLACE_EXISTING)
    }
    println "File saved to: $outputPath"
}
