plugins {
    id("base")
    id("org.openapi.generator")
}

group = "rs.russian.api"

def openApiPath = "$projectDir/../openapi.yaml"
def npmName = "@russian-rs/portal-api-axios"
def npmVersion = resolveApiVersion()
def npmRepository = "https://npm.pkg.github.com"

if (project.hasProperty('snapshot')) {
    npmVersion = "${resolveApiVersion()}-snapshot-${snapshot}"
}

openApiGenerate {
    generatorName = "typescript-axios"
    inputSpec = openApiPath
    outputDir = "${projectDir}/build"
    templateDir = "${projectDir}/templates"
    typeMappings = [
            "set": "Array"
    ]
    configOptions = [
            "npmName"      : npmName,
            "npmVersion"   : npmVersion,
            "npmRepository": npmRepository
    ]
}


build {
    dependsOn(tasks.named("openApiGenerate"))
}
