--- # Common
server:
  error:
    include-message: always

app:
  frontend-uri: http://localhost:3000
  s3:
    region: eu-central
    endpoint: http://localhost:9000
    bucket: portal-files
    bucket-service: portal-data
  wordpress:
    base-url: http://localhost
  schedulers:
    email-outbox: "-"
    user-sync: "-"

ds:
  cf:
    turnstile:
      url: http://localhost:${server.port}/turnstile

--- # Data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portal?ApplicationName=${spring.application.name}&targetServerType=master
    username: admin
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0

--- # Security
spring:
  security:
    oauth2:
      client:
        registration:
          authentik:
            redirect-uri: http://localhost:3000/api/oauth2/code

--- # Mail
spring:
  mail:
    host: localhost
    username: change
    password: change

--- # Logging
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
  config: classpath:logback-local.xml
