openapi: 3.0.1
info:
  title: volunteer-portal-api
  version: 1.0.0
  contact:
    email: dev@russian.rs
    url: https://russian.rs

servers:
  - url: https://portal-test.russian.rs/api
    description: Test Environment
  - url: https://portal.russian.rs/api
    description: Prod Environment

tags:
  - name: user
    'x-displayName': User

paths:
  /user/info:
    get:
      operationId: info
      tags:
        - user
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
components:
  schemas:
    ErrorResponse:
      type: object
      description: Common object for error responses
      required:
        - code
        - message
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
          description: Error description
          nullable: false
    ErrorCode:
      type: string
      enum:
        - AUTHENTICATION_FAILED
        - BAD_CREDENTIALS
        - CREDENTIALS_EXPIRED
    UserInfo:
      type: object
      description: User info
      required:
        - id
        - username
        - email
        - fullName
      properties:
        id:
          type: string
          nullable: false
        username:
          type: string
          nullable: false
        email:
          type: string
          nullable: false
        fullName:
          type: string
          nullable: false
