name: Coolify Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: install jq
        run: sudo apt-get install jq
      - name: start deploy
        id: start_deploy
        run: |
          response=$(curl -s --request GET '${{ secrets.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_SERVICE_ID }}&force=false' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
          deployment_uuid=$(echo $response | jq -r '.deployments[0].deployment_uuid')
          if [[ $deployment_uuid == "null" ]]; then
            printf "Failed to start deployment: \n$response"
            exit 1
          fi
          echo "deployment_uuid=$deployment_uuid" >> $GITHUB_OUTPUT
      - name: checking status
        run: |
          deployment_uuid=${{ steps.vars.outputs.deployment_uuid }}
          status=""
          deployment_url=""
          
          period=10 # 10 seconds
          max_count=30 # 5 minutes
          
          count=0
          while [ "$status" != "finished" ] && [ "$count" -lt "$max_count" ]
          do
            sleep $period
            count=$(( $count + 1 ))
            response=$(curl -s --request GET '${{ secrets.COOLIFY_API_URL }}/api/v1/deployments/$deployment_uuid' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}')
            status=$(echo $response | jq -r '.status')
            echo "STATUS - $status"
            if [[ $status == "null" ]]; then
              printf "Deployment failed: \n$response"
              exit 1
            fi
            deployment_url=$(echo $response | jq -r '.deployment_url')
          done
          
          if [ "$status" != "deployed" ]; then
            printf "Deployment failed after 5 minutes. \nMore info at ${{ secrets.COOLIFY_API_URL }}/$deployment_url"
            exit 1
          fi
          
          printf "Deployment finished successfully. More info at ${{ secrets.COOLIFY_API_URL }}/$deployment_url"
