name: Publish API

on:
  push:
    paths:
      - api/**
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test
        run: echo ${{ env.GITHUB_REF_NAME }}
      - name: Generate API
        if: ${{ env.GITHUB_REF_NAME == 'main' }}
        run: ./gradlew clean axios-client:build -x test
      - name: Generate snapshot API
        if: ${{ env.GITHUB_REF_NAME != 'main' }}
        run: ./gradlew clean axios-client:build -x test -Psnapshot=${{ env.GITHUB_SHA }}
      - name: Publish NPM package
        working-directory: ./api/axios-client/build
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > .npmrc
          npm install
          npm publish
